#!/usr/bin/env python3
"""Build greatest-songs-2020s.csv from 2020s #1 chart data.

Sources:
  - Billboard Hot 100 #1s 2020-2026 (year-end lists)
  - Billboard Mainstream Rock #1s 2020-2026
  - Billboard Alternative Airplay #1s 2020-2026
  - Billboard Hot Hard Rock #1s 2020-2026 (chart launched 2020)
"""
import re
import os

CSV_PATH = os.path.join(os.path.dirname(__file__), "charts", "greatest-songs-2020s.csv")

# ── Billboard Hot 100 #1s 2020-2026 ──────────────────────────────────
# Only the first time each song reached #1 is included (no returns)
hot100 = [
    # 2020
    ("the box", "roddy ricch"),
    ("blinding lights", "the weeknd"),
    ("toosie slide", "drake"),
    ("the scotts", "the scotts"),
    ("say so", "doja cat feat. nicki minaj"),
    ("stuck with u", "ariana grande and justin bieber"),
    ("savage", "megan thee stallion feat. beyonce"),
    ("rain on me", "lady gaga and ariana grande"),
    ("rockstar", "dababy feat. roddy ricch"),
    ("trollz", "6ix9ine and nicki minaj"),
    ("cardigan", "taylor swift"),
    ("watermelon sugar", "harry styles"),
    ("wap", "cardi b feat. megan thee stallion"),
    ("dynamite", "bts"),
    ("franchise", "travis scott feat. young thug and m.i.a."),
    ("savage love (laxed - siren beat)", "jawsh 685, jason derulo and bts"),
    ("mood", "24kgoldn feat. iann dior"),
    ("positions", "ariana grande"),
    ("life goes on", "bts"),
    ("willow", "taylor swift"),
    # 2021
    ("drivers license", "olivia rodrigo"),
    ("what's next", "drake"),
    ("up", "cardi b"),
    ("peaches", "justin bieber feat. daniel caesar and giveon"),
    ("montero (call me by your name)", "lil nas x"),
    ("leave the door open", "silk sonic"),
    ("rapstar", "polo g"),
    ("save your tears", "the weeknd and ariana grande"),
    ("good 4 u", "olivia rodrigo"),
    ("butter", "bts"),
    ("permission to dance", "bts"),
    ("stay", "the kid laroi and justin bieber"),
    ("way 2 sexy", "drake feat. future and young thug"),
    ("my universe", "coldplay and bts"),
    ("industry baby", "lil nas x and jack harlow"),
    ("easy on me", "adele"),
    ("all too well (taylor's version)", "taylor swift"),
    # 2022
    ("we don't talk about bruno", "carolina gaitan, mauro castillo, adassa, rhenzy feliz, diane guerrero, stephanie beatriz and the encanto cast"),
    ("heat waves", "glass animals"),
    ("as it was", "harry styles"),
    ("first class", "jack harlow"),
    ("wait for u", "future feat. drake and tems"),
    ("jimmy cooks", "drake feat. 21 savage"),
    ("about damn time", "lizzo"),
    ("break my soul", "beyonce"),
    ("super freaky girl", "nicki minaj"),
    ("bad habit", "steve lacy"),
    ("unholy", "sam smith and kim petras"),
    ("anti-hero", "taylor swift"),
    # 2023
    ("flowers", "miley cyrus"),
    ("die for you", "the weeknd and ariana grande"),
    ("last night", "morgan wallen"),
    ("like crazy", "jimin"),
    ("kill bill", "sza"),
    ("vampire", "olivia rodrigo"),
    ("seven", "jung kook feat. latto"),
    ("try that in a small town", "jason aldean"),
    ("rich men north of richmond", "oliver anthony music"),
    ("i remember everything", "zach bryan feat. kacey musgraves"),
    ("paint the town red", "doja cat"),
    ("slime you out", "drake feat. sza"),
    ("first person shooter", "drake feat. j. cole"),
    ("cruel summer", "taylor swift"),
    ("is it over now?", "taylor swift"),
    ("lovin on me", "jack harlow"),
    ("rockin' around the christmas tree", "brenda lee"),
    # 2024
    ("yes, and?", "ariana grande"),
    ("hiss", "megan thee stallion"),
    ("texas hold 'em", "beyonce"),
    ("carnival", "ye and ty dolla sign feat. rich the kid and playboi carti"),
    ("we can't be friends (wait for your love)", "ariana grande"),
    ("lose control", "teddy swims"),
    ("like that", "future, metro boomin and kendrick lamar"),
    ("too sweet", "hozier"),
    ("fortnight", "taylor swift feat. post malone"),
    ("not like us", "kendrick lamar"),
    ("i had some help", "post malone feat. morgan wallen"),
    ("please please please", "sabrina carpenter"),
    ("a bar song (tipsy)", "shaboozey"),
    ("love somebody", "morgan wallen"),
    ("squabble up", "kendrick lamar"),
    # 2025
    ("die with a smile", "lady gaga and bruno mars"),
    ("4x4", "travis scott"),
    ("luther", "kendrick lamar and sza"),
    ("what i want", "morgan wallen feat. tate mcrae"),
    ("ordinary", "alex warren"),
    ("manchild", "sabrina carpenter"),
    ("golden", "huntrix"),
    ("the fate of ophelia", "taylor swift"),
    # 2026 (through July)
    ("i just might", "bruno mars"),
    ("aperture", "harry styles"),
    ("choosin' texas", "ella langley"),
    ("dtmf", "bad bunny"),
    ("opalite", "taylor swift"),
    ("swim", "bts"),
    ("drop dead", "olivia rodrigo"),
    ("janice stfu", "drake"),
    ("hate that i made you love me", "ariana grande"),
    ("i knew it, i knew you", "taylor swift"),
]

# ── Billboard Mainstream Rock #1s 2020-2026 ──────────────────────────
# First occurrence only (no returns / multi-week repeats)
mainstream_rock = [
    ("under the graveyard", "ozzy osbourne"),
    ("killing me slowly", "bad wolves"),
    ("attention attention", "shinedown"),
    ("inside out", "five finger death punch"),
    ("history of violence", "theory of a deadman"),
    ("die to live", "volbeat featuring neil fallon"),
    ("hurricane", "i prevail"),
    ("oh yeah!", "green day"),
    ("far away", "breaking benjamin featuring scooter ward"),
    ("popular monster", "falling in reverse"),
    ("unforgettable", "godsmack"),
    ("sober", "bad wolves"),
    ("a little bit off", "five finger death punch"),
    ("death by rock and roll", "the pretty reckless"),
    ("atlas falls", "shinedown"),
    ("all within my hands", "metallica and san francisco symphony"),
    ("patience", "chris cornell"),
    ("dangerous", "seether"),
    ("black eyes blue", "corey taylor"),
    ("shot in the dark", "ac/dc"),
    ("shame shame", "foo fighters"),
    ("my way, soon", "greta van fleet"),
    ("living the dream", "five finger death punch"),
    ("trouble's coming", "royal blood"),
    ("distance", "mammoth wvh"),
    ("the ending", "papa roach"),
    ("self destructor", "chevelle"),
    ("waiting on a war", "foo fighters"),
    ("and so it went", "the pretty reckless featuring tom morello"),
    ("breathe again", "pop evil"),
    ("bruised and bloodied", "seether"),
    ("let the bad times roll", "the offspring"),
    ("mercy", "ayron jones"),
    ("darkness settles in", "five finger death punch"),
    ("nowhere generation", "rise against"),
    ("for the glory", "all good things featuring johnny 3 tears and charlie scene"),
    ("wait a minute my girl", "volbeat"),
    ("don't back down", "mammoth wvh"),
    ("making a fire", "foo fighters"),
    ("only love can save me now", "the pretty reckless featuring kim thayil and matt cameron"),
    ("survivor", "pop evil"),
    ("wasteland", "seether"),
    ("back from the dead", "halestorm"),
    ("alone again", "asking alexandria"),
    ("kill the noise", "papa roach"),
    ("shotgun blues", "volbeat"),
    ("hunter's moon", "ghost"),
    ("dead inside", "nita strauss and david draiman"),
    ("so called life", "three days grace"),
    ("planet zero", "shinedown"),
    ("zombified", "falling in reverse"),
    ("won't stand down", "muse"),
    ("dead man walking", "jelly roll"),
    ("call me little sunshine", "ghost"),
    ("the steeple", "halestorm"),
    ("afterlife", "five finger death punch"),
    ("lifetime", "three days grace"),
    ("patient number 9", "ozzy osbourne featuring jeff beck"),
    ("daylight", "shinedown"),
    ("hey you", "disturbed"),
    ("no apologies", "papa roach"),
    ("times like these", "five finger death punch"),
    ("masterpiece", "motionless in white"),
    ("natural born killer", "highly suspect"),
    ("bad things", "i prevail"),
    ("surrender", "godsmack"),
    ("lux aeterna", "metallica"),
    ("welcome to the circus", "five finger death punch"),
    ("just pretend", "bad omens"),
    ("lost", "linkin park"),
    ("cut the line", "papa roach"),
    ("rescued", "foo fighters"),
    ("72 seasons", "metallica"),
    ("need a favor", "jelly roll"),
    ("lowest in me", "staind"),
    ("unstoppable", "disturbed"),
    ("the dirt i'm buried in", "avatar"),
    ("blood in the water", "ayron jones"),
    ("beyond", "corey taylor"),
    ("under you", "foo fighters"),
    ("psycho", "asking alexandria"),
    ("too far gone?", "metallica"),
    ("skeletons", "pop evil"),
    ("might love myself", "beartooth"),
    ("the american dream is killing me", "green day"),
    ("a symptom of being human", "shinedown"),
    ("artificial", "daughtry"),
    ("leave a light on (talk away the dark)", "papa roach"),
    ("dark matter", "pearl jam"),
    ("the glass", "foo fighters"),
    ("friendly fire", "linkin park"),
    ("dilemma", "green day"),
    ("i was alive", "beartooth"),
    ("screaming suicide", "metallica"),
    ("truth", "godsmack"),
    ("this is the way", "five finger death punch featuring dmx"),
    ("if it doesn't hurt", "nothing more"),
    ("wreckage", "pearl jam"),
    ("all my life", "falling in reverse featuring jelly roll"),
    ("magnetic", "wage war"),
    ("pieces", "daughtry"),
    ("judas mind", "seether"),
    ("can u see me in the dark?", "halestorm and i prevail"),
    ("the emptiness machine", "linkin park"),
    ("suffocate city", "the funeral portrait featuring spencer charnas"),
    ("angel song", "nothing more featuring david draiman"),
    ("liar", "jelly roll"),
    ("awaken", "breaking benjamin"),
    ("mayday", "three days grace"),
    ("heavy is the crown", "linkin park"),
    ("stuck in my head", "sleep theory"),
    ("bad guy", "falling in reverse featuring saraya"),
    ("dance, kid, dance", "shinedown"),
    ("even if it kills me", "papa roach"),
    ("i will not break", "disturbed"),
    ("house on sand", "nothing more featuring eric vanlerberghe"),
    ("by a monster's hand", "volbeat"),
    ("up from the bottom", "linkin park"),
    ("holy water", "the funeral portrait featuring ivan moody"),
    ("afterlife", "evanescence"),
    ("apologies", "three days grace"),
    ("i refuse", "five finger death punch featuring maria brink"),
    ("the end", "mammoth"),
    ("freefall", "nothing more featuring chris daughtry"),
    ("static", "sleep theory"),
    ("my mind is a mountain", "deftones"),
    ("killing fields", "shinedown"),
    ("everything ends", "architects"),
    ("braindead", "papa roach featuring toby morse"),
    ("specter", "bad omens"),
    ("time will heal", "volbeat"),
    ("for i am death", "the pretty reckless"),
    ("asking for a friend", "foo fighters"),
    ("kill me fast", "three days grace"),
    ("dark thoughts", "the funeral portrait"),
    ("the spell", "mammoth"),
    ("dying to love", "bad omens"),
    ("end of you", "poppy, amy lee and courtney laplante"),
    ("the bottom", "daughtry"),
    ("searchlight", "shinedown"),
    ("wake up calling", "papa roach"),
    ("so far so fake", "pierce the veil"),
    ("your favorite toy", "foo fighters"),
    ("demonic depression", "volbeat"),
    ("crawl back to my coffin", "dayseeker"),
    ("drag me", "from ashes to new"),
    ("safe and sound", "shinedown"),
    ("words are worthless", "sleep theory"),
    ("when i wake up", "the pretty reckless"),
    ("who will you follow", "evanescence"),
    ("twisting the knife", "ice nine kills featuring mckenna grace"),
]

# ── Billboard Alternative Airplay #1s 2020-2026 ──────────────────────
# First occurrence only
alt_airplay = [
    ("orphans", "coldplay"),
    ("dissolve", "absofacto"),
    ("running up that hill", "meg myers"),
    ("might be right", "white reaper"),
    ("everything i wanted", "billie eilish"),
    ("novocaine", "the unlikely candidates"),
    ("cradles", "sub urban"),
    ("oh yeah!", "green day"),
    ("caution", "the killers"),
    ("level of concern", "twenty one pilots"),
    ("honeybee", "the head and the heart"),
    ("hero", "weezer"),
    ("hallucinogenics", "matt maeson"),
    ("monsters", "all time low featuring blackbear"),
    ("leave me alone", "i dont know how but they found me"),
    ("fire for you", "cannons"),
    ("therefore i am", "billie eilish"),
    ("skin and bones", "cage the elephant"),
    ("my ex's best friend", "machine gun kelly featuring blackbear"),
    ("heat waves", "glass animals"),
    ("follow you", "imagine dragons"),
    ("shy away", "twenty one pilots"),
    ("all my favorite songs", "weezer"),
    ("we are between", "modest mouse"),
    ("saturday", "twenty one pilots"),
    ("beggin'", "maneskin"),
    ("brightside", "the lumineers"),
    ("the outside", "twenty one pilots"),
    ("enemy", "imagine dragons and jid"),
    ("black summer", "red hot chili peppers"),
    ("wild child", "the black keys"),
    ("love brand new", "bob moses"),
    ("a little bit of love", "weezer"),
    ("toxic", "boywithuke"),
    ("viva las vengeance", "panic! at the disco"),
    ("supermodel", "maneskin"),
    ("boy", "the killers"),
    ("tippa my tongue", "red hot chili peppers"),
    ("here to forever", "death cab for cutie"),
    ("sex, drugs, etc.", "beach weather"),
    ("edging", "blink-182"),
    ("this is why", "paramore"),
    ("sleepwalking", "all time low"),
    ("records", "weezer"),
    ("love from the other side", "fall out boy"),
    ("lost", "linkin park"),
    ("rescued", "foo fighters"),
    ("emergency contact", "pierce the veil"),
    ("rescue me", "dirty heads"),
    ("just pretend", "bad omens"),
    ("dial drunk", "noah kahan and post malone"),
    ("under you", "foo fighters"),
    ("one more time", "blink-182"),
    ("landmines", "sum 41"),
    ("beautiful people (stay high)", "the black keys"),
    ("neon pill", "cage the elephant"),
    ("dilemma", "green day"),
    ("too sweet", "hozier"),
    ("rainbow", "cage the elephant"),
    ("stargazing", "myles smith"),
    ("the emptiness machine", "linkin park"),
    ("that's how i'm feeling", "jack white"),
    ("dopamine", "sum 41"),
    ("sad in carolina", "dexter and the moonrocks"),
    ("can't slow down", "almost monday"),
    ("the line", "twenty one pilots"),
    ("neverender", "justice featuring tame impala"),
    ("same old song", "the lumineers"),
    ("so cold", "balu brigada"),
    ("messy", "lola young"),
    ("metaverse", "cage the elephant"),
    ("rushmere", "mumford & sons"),
    ("the night before", "the black keys"),
    ("god needs the devil", "jonah kagen"),
    ("up from the bottom", "linkin park"),
    ("back to friends", "sombr"),
    ("nice to meet you", "myles smith"),
    ("basic being basic", "djo"),
    ("the contract", "twenty one pilots"),
    ("never enough", "turnstile"),
    ("better days", "yellowcard"),
    ("ensenada", "sublime"),
    ("so far so fake", "pierce the veil"),
    ("the weather", "all time low"),
    ("city walls", "twenty one pilots"),
    ("downstairs", "matt maeson"),
    ("get the message", "the paradox"),
    ("dracula", "tame impala"),
    ("zombie", "yungblud"),
    ("the great divide", "noah kahan"),
    ("doubletake", "edgehill"),
    ("drag path", "twenty one pilots"),
    ("bedroom posters", "yellowcard featuring good charlotte"),
    ("different kind of love", "young the giant"),
    ("until the sun explodes", "sublime"),
    ("freakin' out", "dexter and the moonrocks"),
]

# ── Normalization helper ─────────────────────────────────────────────
def normalize(s: str) -> str:
    """Lowercase, strip leading/trailing whitespace, collapse internal space."""
    s = s.lower().strip()
    s = re.sub(r"\s+", " ", s)
    return s

# ── Deduplication ────────────────────────────────────────────────────
all_entries_raw = hot100 + mainstream_rock + alt_airplay
seen: set[tuple[str, str]] = set()
unique: list[tuple[str, str]] = []

for song, artist in all_entries_raw:
    key = (normalize(artist), normalize(song))
    if key not in seen:
        seen.add(key)
        # Keep original casing as given, trim whitespace
        unique.append((artist.strip(), song.strip()))

# Sort alphabetically by artist, then song
unique.sort(key=lambda x: (normalize(x[0]), normalize(x[1])))

# ── Write CSV ────────────────────────────────────────────────────────
os.makedirs(os.path.dirname(CSV_PATH), exist_ok=True)
with open(CSV_PATH, "w") as f:
    for artist, song in unique:
        f.write(f"{artist},{song}\n")

print(f"Wrote {len(unique)} entries to {CSV_PATH}")
print(f"Skipped {len(all_entries_raw) - len(unique)} duplicates")
